fix: find python executable independed of os

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,4 +2,14 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 turbo run lint
-python -m pre_commit 
+
+if command -v python >/dev/null 2>&1; then
+    PYTHON_EXEC="python"
+elif command -v python3 >/dev/null 2>&1; then
+    PYTHON_EXEC="python3"
+else
+    echo "Error: Python executable not found."
+    exit 1
+fi
+
+"$PYTHON_EXEC" -m pre_commit
